<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJgELGHc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJgELGHc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJgELGHc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJgELGHc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJgELGHc\App_KernelDevDebugContainer([
    'container.build_hash' => 'JgELGHc',
    'container.build_id' => 'e926ab2d',
    'container.build_time' => 1608416669,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJgELGHc');
