<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6ST97g9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6ST97g9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6ST97g9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6ST97g9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6ST97g9\App_KernelDevDebugContainer([
    'container.build_hash' => '6ST97g9',
    'container.build_id' => '4634c056',
    'container.build_time' => 1608495401,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6ST97g9');
